name: Content correction
description: Flag content-related errors
title: '[EDIT]'
labels: "edit :memo:"

body:
  - type: markdown
    id: description
    attributes:
      value: |
        ## Before posting a content correction
        Search existing GitHub issues to make sure the content correction does not already exist:
        https://github.com/XanaduAI/Xanedu-Quantum-Codebook/issues

        # Issue description
        Description of the error - include node number/section and screenshots if relevant.
  - type: textarea
    id: actual
    attributes:
      label: Current content
      description: |
        What is the current content?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected content
      description: |
        What is the expected content?
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      options:
        - label: I have searched exisisting GitHub issues to make sure the issue does not already exist.
          required: true
