name: Feature request
description: Suggest a new feature
labels: "enhancement :sparkles:"

body:
  - type: markdown
    id: description
    attributes:
      value: |
          ## Before posting a feature request
          Search existing GitHub issues to make sure the feature request does not already exist:
          https://github.com/XanaduAI/Xanadu-Quantum-Codebook/issues

          # Feature description
          Description of the feature request - include code snippets and screenshots here if relevant.
  - type: textarea
    id: details
    attributes:
      label: Feature details
      description: |
        What feature would you like to have?
    validations:
      required: true
  - type: textarea
    id: info
    attributes:
      label: Additional information
      description: |
        Please provide any additional information here. Include potential alternative solutions, or workarounds, as well as references, if any.
